server {
    # Google Cloud Run expects us to listen on port 8080
    listen 8080;
    
    # The folder where our React app files will live
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # This is the magic line for React Router:
        # If a file isn't found, send the user to index.html
        try_files $uri $uri/ /index.html;
    }
}
